#!/usr/bin/env bash

if hash sbt 2>/dev/null; then
	echo 'Fetching sbt dependencies...'
        sbt all-dependencies
else
	echo 'sbt not found. Falling back to activator command'
fi

if hash activator 2>/dev/null; then
	echo 'Fetching activator dependencies...'
	activator all-dependencies
else
	echo 'activator not found too... :-('
fi
